name: building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prod:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         node-version: [17.x]
     steps:
       - name: Cache deps
         uses: actions/cache@v3
         with:
           path: ~/.npm
           key: node-modules-${{ hashFiles('**/package-lock.json') }}
       - uses: actions/checkout@v2
       - name: Starting Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}
       - name: install modules
         run: npm i
       - name: build production project
         run: npm run build:prod