name: building
on:
  push:
    branches: [main]
jobs:
  prod:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/projects/react-production
            git pull
            .deploy/deploy.sh
            pm2 restart json-server/index.js

