name: deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          debug: true
          script: |
            cd ~/projects/react-production
            export PATH="/home/demian/.nvm/versions/node/v20.3.0/bin:$PATH"
            git pull
            npm i
            .deploy/deploy.sh
            pm2 restart json-server/index.js
      - name: Output
        run: echo "#Deployment \nWebsite is deployed to ${{ vars.WEBSITE_URL }}" >> $GITHUB_STEP_SUMMARY
