name: testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm i
      - name: unit testing
        run: npm run test:unit

  ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm i
      - name: Install GraphicsMagick Engine
        run: sudo apt-get install -y graphicsmagick
      - name: build storybook
        run: npm run build:storybook
      - name: screenshot testing
        run: npm run test:ui:ci
      - name: Upload difference folder
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: .loki
          path: .loki